# Generated by Django 4.0.4 on 2022-05-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution',
            field=models.CharField(max_length=255),
        ),
    ]
